language: node_js
if: tag IS present OR NOT (branch == master)
node_js:
- node
deploy:
  provider: npm
  email: deven.phillips@gmail.com
  api_key:
    secure: 6XHwxYreKO2JbxfBlKNZfzucBjGCkSA9QpLQ2tsRpZlNgO8zwkCLSuXNyQXpyh2wenAr4WrF/4+YWXm47q797dC1DrSJfefCHoYgDheAPIpmrs4ASzk4GpXuu8fPkkMGHQ99svii8LZHClv9yura0mNuDIArNirfUBqOMmyr+HY++t9IGuufoRgd2eVtmWuEomDner2Qv+VZEE3JpqMMzxKhMFSAbIhWaKskRAKwdUUl5NJpTtrz15y0bB53lPiuAqo0Qz9Y1/kMIblCWPh13Io6run3s4hFcZ0SgKdE+zUV/7IGXw9D8onlo3aqnccF6WJa2mYAsL7CLEX1xQiGoQD5rXVY4ZfDnIs13McmUFqIqijhptVrx7gn0nFDujqc+Xl9sRs3sTmvWSib7logcwGG2E8tIySttPs378/nxmuBFqm6cQLysfDne0VVP1bqSBUGqyl4dyb0hJ4JU00bUPeWXNy8Hy2Y/lHCPqJxwCien72IXxSNA+Ptnm3HTU3Botk2hUoxpNAItvgswlRbrmV08Oinpm4qQmaP3U6Zr7g83SBtcAf5uejfTy1mgMsWffdMCag6ec/paiCQjBJKSyM+9yfqn3n+7sW5VKSnnE7cxyMhHjIqR7g/8VrTmNv5WUe06zJ1JtxPldFPEbVG+dRiBboMbaJTWDCYqIbT64A=
  on:
    tags: true
    repo: InfoSec812/npm-audit-ci-wrapper
addons:
  sonarcloud:
    organization: infosec812-github
    token: "${SONAR_TOKEN}"
script:
- npm run test
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi
- npm run stryker
